### ISSUE TITLE
Plugin crashes when regenerating styles

### ISSUE THREAD

**Issue by dlewand691** [tbrasington/text-to-styles#10]
On Sketch 60.1, when regenerating styles, the plugin crashes sketch. I'm generating about 1400+ styles and the initial generation worked fine. I'll put together a sample file and share ASAP.

**Comment by tbrasington** [comment]
@dlewand691 hi the initial should always be good. It does become more intensive when doing subsequent runs as it has to check for changes. 

When your file is ready I will take a look and see how I can optimise.

**Comment by dlewand691** [comment]
@tbrasington Sure, totally understand. Sorry for the delay getting you the file, was out for the holiday. 

Attached is my test file and associated fonts. After copying the styles, colors and alignments into a new fresh doc, the plugin run and give this message:

![Sketch 2019-12-05 at 12 54 39@2x](https://user-images.githubusercontent.com/1159913/70260574-9311bf80-175e-11ea-8ced-654594c8c3ca.jpg)

No styles are added but the Rendered styles page is created. Not sure why but thought you should know. I've updated to Sketch 61 as well. 

[text-to-styles-test.zip](https://github.com/tbrasington/text-to-styles/files/3928359/text-to-styles-test.zip)

Thanks for the help!

**Comment by tbrasington** [comment]
Hey @dlewand691 no worries, thank you for taking the time to send your file over. 

I had a quick look and the reason it isn't rendering is due to your alignments page being named "Alignment" rather than"Alignments"

I am working on an improvement to the plugin to message when one of pages is missing.

**Comment by dlewand691** [comment]
@tbrasington Ah ha! That helps to pay attention to details. Works now but the rendered text layers were stacked on top of each other. Not a big deal and not sure if it was because of my file setup. 

Your idea of catching page name issues is would be a big help. Another idea would be to have a "first run" feature that could automatically create the needed pages for you with some default alignments, colors, and styles (maybe based on global colors?).

**Comment by tbrasington** [comment]
@dlewand691 it is a bug which I am working on fixing. 

Agree with the first run feature.

**Comment by tbrasington** [comment]
Hi @dlewand691 In version 4.0.0 I have split the creation of the styles out from the rendering of the style sheet which will help a bit with the updating existing documents. There is also the first run feature and a check to see if any pages are missing.

**Comment by dlewand691** [comment]
@tbrasington Fantastic! I'll update and check it out
