### ISSUE TITLE
Seeing that an update is available, but can't download it

### ISSUE THREAD

**Issue by rickcecil** [tbrasington/text-to-styles#13]
It looks like there is an update to the plugin, but when I click "Update" in Sketch, it doesn't do anything. And when I download the latest files from Github, it says that it's still version 4 ... not the new 4.1.

**Comment by tbrasington** [comment]
Skpm failed to publish. I have reverted back to 4.0.0 while I investigate. It was a patch for npm versions so there isn't anything new in it.
