### ISSUE TITLE
Problem with Styles (not generating text styles)

### ISSUE THREAD

**Issue by joaomag17** [tbrasington/text-to-styles#2]
Hey, apparently there should be a problem with the 1st step (Styles Page). I've tried to run the plugin both with the demo file you have in the repo and with a brand new file. Whenever i have styles on the Styles Page, it just removes any existing style but doesn't add the new ones.
If i rename the Styles page to Page 1, i get a sketch notification saying: "0 Styles were created: 0 Styles x 3 colours x 3 alignments.
Using Sketch 52.2 with Text to Styles 2.3.0
Thanks

**Comment by tbrasington** [comment]
Hi @joaomag17 this should be fixed now with Sketch 52.2. 
Let me know if you are still running into problems.

**Comment by joaomag17** [comment]
Thanks a million @tbrasington , working like a charm now! ;)
