### ISSUE TITLE
Boken in Sketch 53

### ISSUE THREAD

**Issue by custa1200** [tbrasington/text-to-styles#3]
This plugin seems broken in sketch 53. After following the instructions I don't have anything really generated on the Rendered Styles page

**Comment by custa1200** [comment]
Actually what has caught me out here is your use of Colours instead of an industry wide acceptance of Color when coding/design. I can say that it should be Colors as I do come from a country where it would normally be written Colour

**Comment by tbrasington** [comment]
Hi @custa1200 fair enough feedback, this is now an option in the latest release.
