### ISSUE TITLE
all rendered styles are using the same typeface

### ISSUE THREAD

**Issue by custa1200** [tbrasington/text-to-styles#6]
I have set up 10 styles, 5 using Gotham Book and 5 using Gotham Bold:

* 5/Book
* 4/Book
* 3/Book
* 2/Book
* 1/Book
* 5/Bold
* 4/Bold
* 3/Bold
* 2/Bold
* 1/Bold

and when I generate them all the Rendered Styles are using Gotham Bold

:(

**Comment by tbrasington** [comment]
Hi @custa1200 can you remove the existing plugin and see if this build works? 
[text-to-styles.sketchplugin.zip](https://github.com/tbrasington/text-to-styles/files/3012325/text-to-styles.sketchplugin.zip)

If it doesn't could you let me know what other plugins you have installed please?

**Comment by custa1200** [comment]
This seems to be ok now
