### ISSUE TITLE
Regenerating Styles unlinks overrides

### ISSUE THREAD

**Issue by custa1200** [tbrasington/text-to-styles#7]
I created a bunch of styles using the plugin and meticulously went through and added the styles to a bunch of symbol overrides. 

When I went back and regenerated the text styles again, Sketch loses all of the set overrides using the same named overrides and reverts them back to default. Does the rendered styles delete the page on every run (and remove all text styles from the document) and then recreate them with the same names but likely different internal ID's?

**Comment by tbrasington** [comment]
Hi 
It does wipe all the existing styles on each run of the plugin. Which in your scenario will be a problem. I need to have a think about preserving ids.

**Comment by AliciaaaRo** [comment]
Hi, I am having the same problem.
It is a great plugin but it would be really useful if you can prevent the ids because that would mean that you can change the primaries colours in the future or the fonts.
Very often I have fonts and colours defined but after showing the first designs to the client I have to change them, so that would mean that all the work having the text organized is gone. 
Thanks a lot for doing this

**Comment by tbrasington** [comment]
If you are up for testing there is a zip file of the plugin in this branch here https://github.com/tbrasington/text-to-styles/blob/feature/merge-stles/text-to-styles.sketchplugin.zip 

This won't clear any unused styles at the moment (I need to work that out) but it may sort out the id issue.

**Comment by tbrasington** [comment]
@custa1200 @AliciaaaRo I have published an update to the plugin that retains the id if the names of the style, colour and alignments are the same. If those change it will make a new id. 

This means you can change the type properties and colours with the style retaining its link.

Let me know if you have any further issues.

**Comment by custa1200** [comment]
Thanx mate, I'll check it out when back to work in the coming week.

**Comment by tbrasington** [comment]
Hey @custa1200 @AliciaaaRo did you get a chance to try it out?

**Comment by AliciaaaRo** [comment]
@tbrasington You're a super star! 😄  
Sorry, I didn't, but I'll try it today and I'll let you know.

**Comment by tbrasington** [comment]
Closing for now. Please reopen if it hasn’t resolved the use case
